package com.app.olxapplication.utilities

object Constants {

    val USER_ADDRESS = "user_address"
    val USER_PHONE = "user_phone"
    val CREATED_DATE = "createdDate"
    val CITY_NAME = "city_name"
    val USER_PHOTO = "user_photo"
    val USER_NAME = "user_name"
    val USER_ID = "user_id"
    val USER_EMAIL = "user_email"
    val SharedPrefName= "OLX"
    val CATEGORIES = "Categories"
    val BRAND = "Brand"
    val YEAR = "year"
    val AD_TITLE = "adtitle"
    val AD_DESCRIPTION = "addescription"
    val CURRENCY_SYMBOL = "₹"
    val KM_DRIVEN = "kmDriven"
    val TYPE = "type"
    val PRICE = "Price"
    val PHONE = "Phone"
    val ADDRESS = "address"
    val KEY = "key"
    val DOCUMENT_ID = "doc_id"
    val CAR = "Car"
    val Bike = "Bike"
    val IMAGE_PATHS= "image_paths"
    val Id = "id"
}